// Copies the few Lucide icons the app uses into src/ui/lucide.ts (inner SVG markup only).
// Lucide is ISC (+ MIT for the Feather-derived parts); the notice is kept in the generated
// file as a /*! legal comment */ that survives minification. See ASSETS.md.
//   node scripts/lucide.mjs
import { readFileSync, writeFileSync } from "node:fs";

const NAMES = [
  "menu", "x", "check", "plus", "images", "image-plus", "search", "inbox", "send", "eye", "message-circle",
  "sparkles", "users", "user-round", "palette", "heart", "log-out", "shield-check", "download", "share-2",
  "copy", "trash-2", "wifi-off", "refresh-cw", "link", "settings", "arrow-right", "lock",
  "thumbs-down", "folder", "folder-plus", "external-link", "pencil",
  "undo-2", "file-x", "hard-drive",
];

const dir = "node_modules/lucide-static";
const version = JSON.parse(readFileSync(`${dir}/package.json`, "utf8")).version;
const out = {};
for (const n of NAMES) {
  const svg = readFileSync(`${dir}/icons/${n}.svg`, "utf8");
  const inner = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"))
    .replace(/\s*\n\s*/g, "").replace(/ \/>/g, "/>").trim();
  out[n] = inner;
}
const body = `/*! @license Lucide icons v${version} (https://lucide.dev) — ISC License, Copyright (c) Lucide Icons and Contributors;
   Feather-derived parts: MIT License, Copyright (c) 2013-2023 Cole Bemis. Generated by scripts/lucide.mjs — do not edit. */
export const LUCIDE: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync("src/ui/lucide.ts", body);
console.log(`wrote src/ui/lucide.ts (${NAMES.length} icons, lucide-static ${version})`);
